# Site settings
title: Maxå°ç«™ğŸ˜‰
SEOTitle: Maxå°ç«™
header-img: img/post-bg-desk.jpg
email: 0xc00005@gmail.com
description: "Maxçš„å°å°åšå®¢ï¼Œä¸å®šæœŸæ›´æ–°ï¼Œä½†æ˜¯å¹²è´§ä»€ä¹ˆçš„å°±æ˜¯æœ‰ç”Ÿä¹‹å¹´äº†....."
keyword: "0xC00005, Jingwei Zhang, Max - Jingwei Zhang, Max Zhang, Max, 2860520591, Atto Musk, Atto, æ£±é•œ"
url: "http://0xC00005.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/0xC000005/0xC000005.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "
0xC00005ï¼Œæ˜¯ğŸç»ç¾é»‘é•¿ç›´ï¼

å‰OIerï¼ŒPythonğŸ¦gcdäº†ï¼Œå’¸é±¼æ•°æ®ç§‘å­¦ç»™ğŸ‘´çˆªå·´ã€‚ä¸å®šæ—¶å†™æ–‡äº§ç²®ã€‚å–œæ¬¢ç»“äº¤å¤§ä½¬äº†ï¼
"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
#weibo_username:     c8137f32d573
#ä½ è¦æ˜¯æ•¢ç¤¾å·¥çš„è¯é‚£å¯¹ä¸èµ·ï¼Œä½ å¦ˆæ­»äº†ï¼
zhihu_username:     wang-li-jun-76-22
github_username:    0xC000005
facebook_username:  0xC00005
jianshu_username:   c8137f32d573
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# è¯„è®ºç³»ç»Ÿ Disqusï¼ˆhttps://disqus.com/ï¼‰
disqus_username: '0xC00005'

# Gitalk
#gitalk:
#  enable: true    #æ˜¯å¦å¼€å¯Gitalkè¯„è®º
#  clientID: cca4e854a42a1b5a84d9  #ç”Ÿæˆçš„clientID
#  clientSecret: 04333bdeb4b282b73efa46d6f3922cbea61be1c0  #åŒä¸Š
#  repo: 0xC000005.github.io     #ä»“åº“åç§°
#  owner: '0xC000005'    #githubç”¨æˆ·å
#  admin: '0xC000005'
#  distractionFreeMode: true #æ˜¯å¦å¯ç”¨ç±»ä¼¼FBçš„é˜´å½±é®ç½©


# ç»Ÿè®¡

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68
#åœ¨åŒ—ç¾è¿ç™¾åº¦ç»Ÿè®¡éƒ½è¦å¢™æ‰çš„å˜›ï¼ŸQAQ

# Google Analytics
ga_track_id: 'UA-112677501-1'            # Format: UA-xxxxxx-xx
ga_domain: auto           # é»˜è®¤çš„æ˜¯ auto, è¿™é‡Œæˆ‘æ˜¯è‡ªå®šä¹‰äº†çš„åŸŸåï¼Œä½ å¦‚æœæ²¡æœ‰è‡ªå·±çš„åŸŸåï¼Œéœ€è¦æ”¹æˆauto





# Featured Tags
featured-tags: true                     # æ˜¯å¦ä½¿ç”¨é¦–é¡µæ ‡ç­¾
featured-condition-size: 1              # ç›¸åŒæ ‡ç­¾æ•°é‡å¤§äºè¿™ä¸ªæ•°ï¼Œæ‰ä¼šå‡ºç°åœ¨é¦–é¡µ



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "ğŸºé€¼ä¹Zhihu",
        href: "https://www.zhihu.com/people/wang-li-jun-76-22/activities"
    },{
        title: "ğŸ‘Œç®€ä¹¦Jianshu",
        href: "https://www.jianshu.com/u/c8137f32d573"
    },{
        title: "ğŸ˜˜æ¥QQæ’©å°å§å§?",
        href: "http://wpa.qq.com/msgrd?v=3&uin=2860520591&site=qq&menu=yes"
    },{
        title: "ğŸ‰å°ç ´ç«™BiliBili",
        href: "https://space.bilibili.com/33057937#/"
    },{
        title: "ğŸˆåŒ—ç¾æ—¥å¸¸instagram",
        href: "https://www.instagram.com/m04.zhang/"
    }
]
